
###
### получение токена CSRF для аутентификации
###
GET http://user01:1111@localhost:8111/authenticationTest.html?csrf




###
### создание проекта
###
#POST http://user01:1111@192.168.1.42:8111/app/rest/projects
POST http://user01:1111@localhost:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 85873c74-920a-4ec8-aac2-b2b911b2882a

{
    "parentProject": {
        "locator": "_Root"
    },
    "name": "name02",
    "id": "id02",
    "copyAllAssociatedSettings": true
}



###
### Create Build Configuration
###
POST http://user01:1111@localhost:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 85873c74-920a-4ec8-aac2-b2b911b2882a

{
  "id": "id02",
  "name": "Print Hello Word",
  "project": {
    "id": "id"
  },
  "steps": {
    "step": [
      {
        "name": "Print Hello",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            }
          ]
        }
      }
    ]
  }
}


###
### Create Build Configuration
###
POST http://user01:1111@localhost:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 85873c74-920a-4ec8-aac2-b2b911b2882a

{
  "id": "id02",
  "name": "Print Hello Word",
  "project": {
    "id": "id02"
  },
  "steps": {
    "step": [
      {
        "name": "Print Hello",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}


###
### Get Build Configuration
###
GET http://user01:1111@localhost:8111/app/rest/buildTypes/id:id
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: f5c0a7b6-8a6f-4c50-bcc5-8fbd0279e8d3



###
### Run Build
###
POST http://user01:1111@localhost:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 1f1270a9-af78-4c3f-968f-2d0e423e14b7

{
  "buildType": {
    "id": "id02"
  }
}


###
### Get Build Details
###
GET http://user01:1111@localhost:8111/app/rest/builds?locator=id:3
Content-Type: application/json
Accept: application/json
#X-TC-CSRF-Token: f5c0a7b6-8a6f-4c50-bcc5-8fbd0279e8d3


###
### Get Build Details. v2
###
GET http://user01:1111@localhost:8111/app/rest/builds/id:3
Content-Type: application/json
Accept: application/json
#X-TC-CSRF-Token: f5c0a7b6-8a6f-4c50-bcc5-8fbd0279e8d3









###




#GET http://admin:admin@localhost:8111/authenticationTest.html?csrf - запрос на
#POST http://admin:admin@localhost:8111/app/rest/projects - запрос на создание прожекта, подробнее тут.
#POST http://admin:admin@localhost:8111/app/rest/buildTypes - запрос на создание конфигурации сборки, подробнее тут.
#POST http://admin:admin@localhost:8111/app/rest/buildQueue - запрос на запуск сборки, подробнее тут.
#GET http://admin:admin@localhost:8111/app/rest/builds - запрос на получение статуса сборки, подробнее тут.














